// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHxPWzVESGjXla2S-ij20suMXZtsDlpxw',
    appId: '1:752565241161:web:ebef38f44e22a4236f4698',
    messagingSenderId: '752565241161',
    projectId: 'finalproject-88025',
    authDomain: 'finalproject-88025.firebaseapp.com',
    storageBucket: 'finalproject-88025.firebasestorage.app',
    measurementId: 'G-XCQQ7M28YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_sahzacdkTj8jEi0XA7XIWZxrwK2-kA',
    appId: '1:752565241161:android:dab3101a9c731c276f4698',
    messagingSenderId: '752565241161',
    projectId: 'finalproject-88025',
    storageBucket: 'finalproject-88025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nDN61P7zWrmB1gsMZ0_ZnEoV63DhOKU',
    appId: '1:752565241161:ios:13f31f30d2c7bd4b6f4698',
    messagingSenderId: '752565241161',
    projectId: 'finalproject-88025',
    storageBucket: 'finalproject-88025.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nDN61P7zWrmB1gsMZ0_ZnEoV63DhOKU',
    appId: '1:752565241161:ios:13f31f30d2c7bd4b6f4698',
    messagingSenderId: '752565241161',
    projectId: 'finalproject-88025',
    storageBucket: 'finalproject-88025.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHxPWzVESGjXla2S-ij20suMXZtsDlpxw',
    appId: '1:752565241161:web:9c3de73599df2c826f4698',
    messagingSenderId: '752565241161',
    projectId: 'finalproject-88025',
    authDomain: 'finalproject-88025.firebaseapp.com',
    storageBucket: 'finalproject-88025.firebasestorage.app',
    measurementId: 'G-V85K71C0G9',
  );

}

